@echo off

set SOURCE_DIRECTORY=navis
set VULKAN_SDK_DIRECTORY=C:/VulkanSDK/1.3.239.0

set OUTPUT_LIBRARY_NAME=navis
set OUTPUT_LIBRARY_EXTENSION=.dll

set MAJOR_VERSION=2023
set MINOR_VERSION=5
set PATCH_VERSION=0

set BINARIES_DIRECTORY=.binaries

set LINKS=""msvcrt.lib" "libcmt.lib""

set BUILD_TARGET=windows_amd64
set BUILD_KIND=shared
set BUILD_DEBUG=false
set BUILD_VERBOSE=false

set BUILD_OS_DIRECTORY_NAME=windows
set BUILD_KIND_DIRECTORY_NAME=shared
set BUILD_MODE_DIRECTORY_NAME=release
set BUILD_ARCH_DIRECTORY_NAME=amd64

for %%a in (%*) do (

    if %%a==-arch:i386 (
        set BUILD_TARGET=windows_i386
        set BUILD_ARCH_DIRECTORY_NAME=i386
    )

    if %%a==-arch:amd64 (
        set BUILD_TARGET=windows_amd64
        set BUILD_ARCH_DIRECTORY_NAME=amd64
    )

    if %%a==-mode:debug (
        set BUILD_DEBUG=true
        set BUILD_MODE_DIRECTORY_NAME=debug
    )

    if %%a==-mode:release (
        set BUILD_DEBUG=false
        set BUILD_MODE_DIRECTORY_NAME=release
    )

    if %%a==-verbose (
        set BUILD_VERBOSE=true
    )
)

set BUILD_DIRECTORY=%BINARIES_DIRECTORY%
set BUILD_DIRECTORY=%BUILD_DIRECTORY%\%BUILD_OS_DIRECTORY_NAME%
set BUILD_DIRECTORY=%BUILD_DIRECTORY%\%BUILD_KIND_DIRECTORY_NAME%
set BUILD_DIRECTORY=%BUILD_DIRECTORY%\%BUILD_ARCH_DIRECTORY_NAME%
set BUILD_DIRECTORY=%BUILD_DIRECTORY%\%BUILD_MODE_DIRECTORY_NAME%

set OUTPUT_LIBRARY_PATH=%BUILD_DIRECTORY%\%OUTPUT_LIBRARY_NAME%%OUTPUT_LIBRARY_EXTENSION%

set BUILD_COMMAND=build
set BUILD_COMMAND=%BUILD_COMMAND% %SOURCE_DIRECTORY%
set BUILD_COMMAND=%BUILD_COMMAND% -build-mode:%BUILD_KIND%
if %BUILD_DEBUG%==true ( set BUILD_COMMAND=%BUILD_COMMAND% -debug)
if %BUILD_KIND%==shared ( set BUILD_COMMAND=%BUILD_COMMAND% -define:NAVIS_API_SHARED=true)
if %BUILD_KIND%==shared ( set BUILD_COMMAND=%BUILD_COMMAND% -define:NAVIS_API_EXPORT=true)
set BUILD_COMMAND=%BUILD_COMMAND% -define:NAVIS_API_VERBOSE=%BUILD_VERBOSE%
set BUILD_COMMAND=%BUILD_COMMAND% -define:NAVIS_API_VERSION_MAJOR=%MAJOR_VERSION%
set BUILD_COMMAND=%BUILD_COMMAND% -define:NAVIS_API_VERSION_MINOR=%MINOR_VERSION%
set BUILD_COMMAND=%BUILD_COMMAND% -define:NAVIS_API_VERSION_PATCH=%PATCH_VERSION%
set BUILD_COMMAND=%BUILD_COMMAND% -collection:%OUTPUT_LIBRARY_NAME%=%SOURCE_DIRECTORY%
set BUILD_COMMAND=%BUILD_COMMAND% -collection:binaries=%BUILD_DIRECTORY%
set BUILD_COMMAND=%BUILD_COMMAND% -collection:vulkan_sdk=%VULKAN_SDK_DIRECTORY%
set BUILD_COMMAND=%BUILD_COMMAND% -extra-linker-flags:%LINKS%
set BUILD_COMMAND=%BUILD_COMMAND% -out:%OUTPUT_LIBRARY_PATH%

if not exist "%BUILD_DIRECTORY%" (
    mkdir %BUILD_DIRECTORY%
)

@echo    Building os:%BUILD_OS_DIRECTORY_NAME% kind:%BUILD_KIND_DIRECTORY_NAME% arch:%BUILD_ARCH_DIRECTORY_NAME% mode:%BUILD_MODE_DIRECTORY_NAME% verbose:%BUILD_VERBOSE%
@odin %BUILD_COMMAND%